// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `WEBAPI.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var WebAPI = __M.module("WebAPI");

    /**
     * @brief  后台管理员信息。
     **/
    WebAPI.Account = Slice.defineStruct(
        function(usernam, password, authority, userid)
        {
            this.usernam = usernam !== undefined ? usernam : "";
            this.password = password !== undefined ? password : "";
            this.authority = authority !== undefined ? authority : 0;
            this.userid = userid !== undefined ? userid : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.usernam);
            __os.writeString(this.password);
            __os.writeInt(this.authority);
            __os.writeInt(this.userid);
        },
        function(__is)
        {
            this.usernam = __is.readString();
            this.password = __is.readString();
            this.authority = __is.readInt();
            this.userid = __is.readInt();
        },
        10, 
        false);

    /**
     * @brief  后端接口返回给前端的单个管理员数据。
     **/
    WebAPI.AcntRslt = Slice.defineStruct(
        function(code, userid, bgmodel, authority)
        {
            this.code = code !== undefined ? code : 0;
            this.userid = userid !== undefined ? userid : 0;
            this.bgmodel = bgmodel !== undefined ? bgmodel : 0;
            this.authority = authority !== undefined ? authority : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            __os.writeInt(this.userid);
            __os.writeInt(this.bgmodel);
            __os.writeInt(this.authority);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.userid = __is.readInt();
            this.bgmodel = __is.readInt();
            this.authority = __is.readInt();
        },
        16, 
        true);
    Slice.defineSequence(WebAPI, "AcntListHelper", "WebAPI.Account", false);

    /**
     * @brief  cms界面查询管理员列表时，返回给前台的管理员信息。
     **/
    WebAPI.AcntListRlt = Slice.defineStruct(
        function(code, rslt)
        {
            this.code = code !== undefined ? code : 0;
            this.rslt = rslt !== undefined ? rslt : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.AcntListHelper.write(__os, this.rslt);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.rslt = WebAPI.AcntListHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  相机信息。
     **/
    WebAPI.CamInfo = Slice.defineStruct(
        function(name, CamIp, camid, campassword, camaddress, camst, rsltnum)
        {
            this.name = name !== undefined ? name : "";
            this.CamIp = CamIp !== undefined ? CamIp : "";
            this.camid = camid !== undefined ? camid : 0;
            this.campassword = campassword !== undefined ? campassword : "";
            this.camaddress = camaddress !== undefined ? camaddress : "";
            this.camst = camst !== undefined ? camst : 0;
            this.rsltnum = rsltnum !== undefined ? rsltnum : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.name);
            __os.writeString(this.CamIp);
            __os.writeInt(this.camid);
            __os.writeString(this.campassword);
            __os.writeString(this.camaddress);
            __os.writeInt(this.camst);
            __os.writeInt(this.rsltnum);
        },
        function(__is)
        {
            this.name = __is.readString();
            this.CamIp = __is.readString();
            this.camid = __is.readInt();
            this.campassword = __is.readString();
            this.camaddress = __is.readString();
            this.camst = __is.readInt();
            this.rsltnum = __is.readInt();
        },
        16, 
        false);
    Slice.defineSequence(WebAPI, "CamsListHelper", "WebAPI.CamInfo", false);

    /**
     * @brief  cms查询后台时，返回给前端的数据。
     **/
    WebAPI.CamsListRlt = Slice.defineStruct(
        function(code, listrslt)
        {
            this.code = code !== undefined ? code : 0;
            this.listrslt = listrslt !== undefined ? listrslt : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.CamsListHelper.write(__os, this.listrslt);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.listrslt = WebAPI.CamsListHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  查询
     **/
    WebAPI.ChkRslt = Slice.defineStruct(
        function(camid, pic, pname, persontype, event)
        {
            this.camid = camid !== undefined ? camid : 0;
            this.pic = pic !== undefined ? pic : "";
            this.pname = pname !== undefined ? pname : "";
            this.persontype = persontype !== undefined ? persontype : 0;
            this.event = event !== undefined ? event : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.camid);
            __os.writeString(this.pic);
            __os.writeString(this.pname);
            __os.writeInt(this.persontype);
            __os.writeInt(this.event);
        },
        function(__is)
        {
            this.camid = __is.readInt();
            this.pic = __is.readString();
            this.pname = __is.readString();
            this.persontype = __is.readInt();
            this.event = __is.readInt();
        },
        14, 
        false);
    Slice.defineSequence(WebAPI, "RsltListHelper", "WebAPI.ChkRslt", false);

    /**
     * @brief  
     **/
    WebAPI.CamST = Slice.defineStruct(
        function(code, rsltnum, rsltlist)
        {
            this.code = code !== undefined ? code : 0;
            this.rsltnum = rsltnum !== undefined ? rsltnum : 0;
            this.rsltlist = rsltlist !== undefined ? rsltlist : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            __os.writeInt(this.rsltnum);
            WebAPI.RsltListHelper.write(__os, this.rsltlist);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.rsltnum = __is.readInt();
            this.rsltlist = WebAPI.RsltListHelper.read(__is);
        },
        9, 
        false);
    Slice.defineSequence(WebAPI, "FileUploadHelper", "Ice.ByteHelper", true);

    /**
     * @brief  
     **/
    WebAPI.FileInfo = Slice.defineStruct(
        function(pic, filetype, persontype, name, sex, birthday, IDNum, jobnum, comingday, comingtime, group, company, city, addr, position, attendance, department)
        {
            this.pic = pic !== undefined ? pic : null;
            this.filetype = filetype !== undefined ? filetype : 0;
            this.persontype = persontype !== undefined ? persontype : 0;
            this.name = name !== undefined ? name : "";
            this.sex = sex !== undefined ? sex : 0;
            this.birthday = birthday !== undefined ? birthday : "";
            this.IDNum = IDNum !== undefined ? IDNum : "";
            this.jobnum = jobnum !== undefined ? jobnum : "";
            this.comingday = comingday !== undefined ? comingday : "";
            this.comingtime = comingtime !== undefined ? comingtime : "";
            this.group = group !== undefined ? group : 0;
            this.company = company !== undefined ? company : 0;
            this.city = city !== undefined ? city : "";
            this.addr = addr !== undefined ? addr : "";
            this.position = position !== undefined ? position : 0;
            this.attendance = attendance !== undefined ? attendance : 0;
            this.department = department !== undefined ? department : 0;
        },
        true,
        function(__os)
        {
            WebAPI.FileUploadHelper.write(__os, this.pic);
            __os.writeInt(this.filetype);
            __os.writeInt(this.persontype);
            __os.writeString(this.name);
            __os.writeInt(this.sex);
            __os.writeString(this.birthday);
            __os.writeString(this.IDNum);
            __os.writeString(this.jobnum);
            __os.writeString(this.comingday);
            __os.writeString(this.comingtime);
            __os.writeInt(this.group);
            __os.writeInt(this.company);
            __os.writeString(this.city);
            __os.writeString(this.addr);
            __os.writeInt(this.position);
            __os.writeInt(this.attendance);
            __os.writeInt(this.department);
        },
        function(__is)
        {
            this.pic = WebAPI.FileUploadHelper.read(__is);
            this.filetype = __is.readInt();
            this.persontype = __is.readInt();
            this.name = __is.readString();
            this.sex = __is.readInt();
            this.birthday = __is.readString();
            this.IDNum = __is.readString();
            this.jobnum = __is.readString();
            this.comingday = __is.readString();
            this.comingtime = __is.readString();
            this.group = __is.readInt();
            this.company = __is.readInt();
            this.city = __is.readString();
            this.addr = __is.readString();
            this.position = __is.readInt();
            this.attendance = __is.readInt();
            this.department = __is.readInt();
        },
        41, 
        false);

    /**
     * @brief  人的信息。
     **/
    WebAPI.PersonInfo = Slice.defineStruct(
        function(type, personid, pname, gender, birth, IDNum, employeenum, entrytime, picdirect, entrydate, group, company, city, addr, position, attendancerule, department, companyid, positionid, attendanceid, departmentid)
        {
            this.type = type !== undefined ? type : 0;
            this.personid = personid !== undefined ? personid : 0;
            this.pname = pname !== undefined ? pname : "";
            this.gender = gender !== undefined ? gender : 0;
            this.birth = birth !== undefined ? birth : "";
            this.IDNum = IDNum !== undefined ? IDNum : "";
            this.employeenum = employeenum !== undefined ? employeenum : "";
            this.entrytime = entrytime !== undefined ? entrytime : "";
            this.picdirect = picdirect !== undefined ? picdirect : "";
            this.entrydate = entrydate !== undefined ? entrydate : "";
            this.group = group !== undefined ? group : 0;
            this.company = company !== undefined ? company : "";
            this.city = city !== undefined ? city : "";
            this.addr = addr !== undefined ? addr : "";
            this.position = position !== undefined ? position : "";
            this.attendancerule = attendancerule !== undefined ? attendancerule : "";
            this.department = department !== undefined ? department : "";
            this.companyid = companyid !== undefined ? companyid : 0;
            this.positionid = positionid !== undefined ? positionid : 0;
            this.attendanceid = attendanceid !== undefined ? attendanceid : 0;
            this.departmentid = departmentid !== undefined ? departmentid : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.type);
            __os.writeInt(this.personid);
            __os.writeString(this.pname);
            __os.writeInt(this.gender);
            __os.writeString(this.birth);
            __os.writeString(this.IDNum);
            __os.writeString(this.employeenum);
            __os.writeString(this.entrytime);
            __os.writeString(this.picdirect);
            __os.writeString(this.entrydate);
            __os.writeInt(this.group);
            __os.writeString(this.company);
            __os.writeString(this.city);
            __os.writeString(this.addr);
            __os.writeString(this.position);
            __os.writeString(this.attendancerule);
            __os.writeString(this.department);
            __os.writeInt(this.companyid);
            __os.writeInt(this.positionid);
            __os.writeInt(this.attendanceid);
            __os.writeInt(this.departmentid);
        },
        function(__is)
        {
            this.type = __is.readInt();
            this.personid = __is.readInt();
            this.pname = __is.readString();
            this.gender = __is.readInt();
            this.birth = __is.readString();
            this.IDNum = __is.readString();
            this.employeenum = __is.readString();
            this.entrytime = __is.readString();
            this.picdirect = __is.readString();
            this.entrydate = __is.readString();
            this.group = __is.readInt();
            this.company = __is.readString();
            this.city = __is.readString();
            this.addr = __is.readString();
            this.position = __is.readString();
            this.attendancerule = __is.readString();
            this.department = __is.readString();
            this.companyid = __is.readInt();
            this.positionid = __is.readInt();
            this.attendanceid = __is.readInt();
            this.departmentid = __is.readInt();
        },
        45, 
        false);
    Slice.defineSequence(WebAPI, "PerInfoListHelper", "WebAPI.PersonInfo", false);

    /**
     * @brief  包含id和type。type表示人员类型，包括员工、管理层、访客和陌生人。
     * 不同类型的人员保存在不同的数据表中，id表示各个表中的id。
     **/
    WebAPI.PersonIdType = Slice.defineStruct(
        function(personId, personType)
        {
            this.personId = personId !== undefined ? personId : 0;
            this.personType = personType !== undefined ? personType : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.personId);
            __os.writeInt(this.personType);
        },
        function(__is)
        {
            this.personId = __is.readInt();
            this.personType = __is.readInt();
        },
        8, 
        true);

    /**
     * @brief  用于根据员工id，修改员工信息的接口。
     **/
    WebAPI.Mpic = Slice.defineStruct(
        function(persoind, personType, newpic)
        {
            this.persoind = persoind !== undefined ? persoind : 0;
            this.personType = personType !== undefined ? personType : 0;
            this.newpic = newpic !== undefined ? newpic : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.persoind);
            __os.writeInt(this.personType);
            WebAPI.FileUploadHelper.write(__os, this.newpic);
        },
        function(__is)
        {
            this.persoind = __is.readInt();
            this.personType = __is.readInt();
            this.newpic = WebAPI.FileUploadHelper.read(__is);
        },
        9, 
        false);

    /**
     * @brief  员工信息接口的返回结果。
     **/
    WebAPI.PeoST = Slice.defineStruct(
        function(code, infolist)
        {
            this.code = code !== undefined ? code : 0;
            this.infolist = infolist !== undefined ? infolist : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.PerInfoListHelper.write(__os, this.infolist);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.infolist = WebAPI.PerInfoListHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  查询打卡记录的输入。
     **/
    WebAPI.HisInfo = Slice.defineStruct(
        function(name, employeenum, IDNum, group, type, starttime, endtime, personid, pageNum, pageSize)
        {
            this.name = name !== undefined ? name : "";
            this.employeenum = employeenum !== undefined ? employeenum : "";
            this.IDNum = IDNum !== undefined ? IDNum : "";
            this.group = group !== undefined ? group : 0;
            this.type = type !== undefined ? type : 0;
            this.starttime = starttime !== undefined ? starttime : "";
            this.endtime = endtime !== undefined ? endtime : "";
            this.personid = personid !== undefined ? personid : 0;
            this.pageNum = pageNum !== undefined ? pageNum : 0;
            this.pageSize = pageSize !== undefined ? pageSize : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.name);
            __os.writeString(this.employeenum);
            __os.writeString(this.IDNum);
            __os.writeInt(this.group);
            __os.writeInt(this.type);
            __os.writeString(this.starttime);
            __os.writeString(this.endtime);
            __os.writeInt(this.personid);
            __os.writeInt(this.pageNum);
            __os.writeInt(this.pageSize);
        },
        function(__is)
        {
            this.name = __is.readString();
            this.employeenum = __is.readString();
            this.IDNum = __is.readString();
            this.group = __is.readInt();
            this.type = __is.readInt();
            this.starttime = __is.readString();
            this.endtime = __is.readString();
            this.personid = __is.readInt();
            this.pageNum = __is.readInt();
            this.pageSize = __is.readInt();
        },
        25, 
        false);

    /**
     * @brief  查询打卡记录的返回。
     **/
    WebAPI.HisAcrd = Slice.defineStruct(
        function(hisid, pic, name, employeenum, IDNum, group, type, gender, acrddate, acrdtime, camname, personid, picid, camid)
        {
            this.hisid = hisid !== undefined ? hisid : 0;
            this.pic = pic !== undefined ? pic : "";
            this.name = name !== undefined ? name : "";
            this.employeenum = employeenum !== undefined ? employeenum : "";
            this.IDNum = IDNum !== undefined ? IDNum : "";
            this.group = group !== undefined ? group : 0;
            this.type = type !== undefined ? type : 0;
            this.gender = gender !== undefined ? gender : 0;
            this.acrddate = acrddate !== undefined ? acrddate : "";
            this.acrdtime = acrdtime !== undefined ? acrdtime : "";
            this.camname = camname !== undefined ? camname : "";
            this.personid = personid !== undefined ? personid : 0;
            this.picid = picid !== undefined ? picid : 0;
            this.camid = camid !== undefined ? camid : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.hisid);
            __os.writeString(this.pic);
            __os.writeString(this.name);
            __os.writeString(this.employeenum);
            __os.writeString(this.IDNum);
            __os.writeInt(this.group);
            __os.writeInt(this.type);
            __os.writeInt(this.gender);
            __os.writeString(this.acrddate);
            __os.writeString(this.acrdtime);
            __os.writeString(this.camname);
            __os.writeInt(this.personid);
            __os.writeInt(this.picid);
            __os.writeInt(this.camid);
        },
        function(__is)
        {
            this.hisid = __is.readInt();
            this.pic = __is.readString();
            this.name = __is.readString();
            this.employeenum = __is.readString();
            this.IDNum = __is.readString();
            this.group = __is.readInt();
            this.type = __is.readInt();
            this.gender = __is.readInt();
            this.acrddate = __is.readString();
            this.acrdtime = __is.readString();
            this.camname = __is.readString();
            this.personid = __is.readInt();
            this.picid = __is.readInt();
            this.camid = __is.readInt();
        },
        35, 
        false);
    Slice.defineSequence(WebAPI, "AccordsHelper", "WebAPI.HisAcrd", false);

    /**
     * @brief  查询打卡记录的返回结果。
     **/
    WebAPI.AcrdQueryRslt = Slice.defineStruct(
        function(code, pageNum, pageSize, totalCount, hisacrds)
        {
            this.code = code !== undefined ? code : 0;
            this.pageNum = pageNum !== undefined ? pageNum : 0;
            this.pageSize = pageSize !== undefined ? pageSize : 0;
            this.totalCount = totalCount !== undefined ? totalCount : 0;
            this.hisacrds = hisacrds !== undefined ? hisacrds : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            __os.writeInt(this.pageNum);
            __os.writeInt(this.pageSize);
            __os.writeInt(this.totalCount);
            WebAPI.AccordsHelper.write(__os, this.hisacrds);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.pageNum = __is.readInt();
            this.pageSize = __is.readInt();
            this.totalCount = __is.readInt();
            this.hisacrds = WebAPI.AccordsHelper.read(__is);
        },
        17, 
        false);

    /**
     * @brief  用于设置历史记录中的人到黑白名单。
     **/
    WebAPI.GroupModefy = Slice.defineStruct(
        function(hisid, group)
        {
            this.hisid = hisid !== undefined ? hisid : 0;
            this.group = group !== undefined ? group : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.hisid);
            __os.writeInt(this.group);
        },
        function(__is)
        {
            this.hisid = __is.readInt();
            this.group = __is.readInt();
        },
        8, 
        true);

    /**
     * @brief  公司信息。
     **/
    WebAPI.CompInfo = Slice.defineStruct(
        function(companyid, name)
        {
            this.companyid = companyid !== undefined ? companyid : 0;
            this.name = name !== undefined ? name : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.companyid);
            __os.writeString(this.name);
        },
        function(__is)
        {
            this.companyid = __is.readInt();
            this.name = __is.readString();
        },
        5, 
        false);
    Slice.defineSequence(WebAPI, "CompanyNamesHelper", "WebAPI.CompInfo", false);

    WebAPI.OperST = Slice.defineStruct(
        function(code, comp)
        {
            this.code = code !== undefined ? code : 0;
            this.comp = comp !== undefined ? comp : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.CompanyNamesHelper.write(__os, this.comp);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.comp = WebAPI.CompanyNamesHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  部门信息。
     **/
    WebAPI.DeptInfo = Slice.defineStruct(
        function(departmentid, name)
        {
            this.departmentid = departmentid !== undefined ? departmentid : 0;
            this.name = name !== undefined ? name : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.departmentid);
            __os.writeString(this.name);
        },
        function(__is)
        {
            this.departmentid = __is.readInt();
            this.name = __is.readString();
        },
        5, 
        false);
    Slice.defineSequence(WebAPI, "DeptNamsHelper", "WebAPI.DeptInfo", false);

    WebAPI.DeptST = Slice.defineStruct(
        function(code, dept)
        {
            this.code = code !== undefined ? code : 0;
            this.dept = dept !== undefined ? dept : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.DeptNamsHelper.write(__os, this.dept);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.dept = WebAPI.DeptNamsHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  职位信息。
     **/
    WebAPI.PositInfo = Slice.defineStruct(
        function(positionid, name)
        {
            this.positionid = positionid !== undefined ? positionid : 0;
            this.name = name !== undefined ? name : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.positionid);
            __os.writeString(this.name);
        },
        function(__is)
        {
            this.positionid = __is.readInt();
            this.name = __is.readString();
        },
        5, 
        false);
    Slice.defineSequence(WebAPI, "PositNamsHelper", "WebAPI.PositInfo", false);

    WebAPI.PositST = Slice.defineStruct(
        function(code, posit)
        {
            this.code = code !== undefined ? code : 0;
            this.posit = posit !== undefined ? posit : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.PositNamsHelper.write(__os, this.posit);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.posit = WebAPI.PositNamsHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  签到规则。
     **/
    WebAPI.AttendRuleInfo = Slice.defineStruct(
        function(ruleid, rulename, alcheckin, checkin, checkout, lacheckout, mealtime, worktime)
        {
            this.ruleid = ruleid !== undefined ? ruleid : 0;
            this.rulename = rulename !== undefined ? rulename : "";
            this.alcheckin = alcheckin !== undefined ? alcheckin : "";
            this.checkin = checkin !== undefined ? checkin : "";
            this.checkout = checkout !== undefined ? checkout : "";
            this.lacheckout = lacheckout !== undefined ? lacheckout : "";
            this.mealtime = mealtime !== undefined ? mealtime : 0.0;
            this.worktime = worktime !== undefined ? worktime : 0.0;
        },
        false,
        function(__os)
        {
            __os.writeInt(this.ruleid);
            __os.writeString(this.rulename);
            __os.writeString(this.alcheckin);
            __os.writeString(this.checkin);
            __os.writeString(this.checkout);
            __os.writeString(this.lacheckout);
            __os.writeDouble(this.mealtime);
            __os.writeDouble(this.worktime);
        },
        function(__is)
        {
            this.ruleid = __is.readInt();
            this.rulename = __is.readString();
            this.alcheckin = __is.readString();
            this.checkin = __is.readString();
            this.checkout = __is.readString();
            this.lacheckout = __is.readString();
            this.mealtime = __is.readDouble();
            this.worktime = __is.readDouble();
        },
        25, 
        false);
    Slice.defineSequence(WebAPI, "RuleListHelper", "WebAPI.AttendRuleInfo", false);

    WebAPI.AttRuleSt = Slice.defineStruct(
        function(code, rulelist)
        {
            this.code = code !== undefined ? code : 0;
            this.rulelist = rulelist !== undefined ? rulelist : null;
        },
        false,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.RuleListHelper.write(__os, this.rulelist);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.rulelist = WebAPI.RuleListHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  签到查询的输入。
     **/
    WebAPI.AAQueryInfo = Slice.defineStruct(
        function(name, employeenum, department, starttime, endtime, pageNum, pageSize)
        {
            this.name = name !== undefined ? name : "";
            this.employeenum = employeenum !== undefined ? employeenum : "";
            this.department = department !== undefined ? department : 0;
            this.starttime = starttime !== undefined ? starttime : "";
            this.endtime = endtime !== undefined ? endtime : "";
            this.pageNum = pageNum !== undefined ? pageNum : 0;
            this.pageSize = pageSize !== undefined ? pageSize : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.name);
            __os.writeString(this.employeenum);
            __os.writeInt(this.department);
            __os.writeString(this.starttime);
            __os.writeString(this.endtime);
            __os.writeInt(this.pageNum);
            __os.writeInt(this.pageSize);
        },
        function(__is)
        {
            this.name = __is.readString();
            this.employeenum = __is.readString();
            this.department = __is.readInt();
            this.starttime = __is.readString();
            this.endtime = __is.readString();
            this.pageNum = __is.readInt();
            this.pageSize = __is.readInt();
        },
        16, 
        false);

    /**
     * @brief  单个签到情况的数据结构。
     **/
    WebAPI.AAQRslt = Slice.defineStruct(
        function(date, name, employeenum, department, checkin, checkout, attendrule, attendresult)
        {
            this.date = date !== undefined ? date : "";
            this.name = name !== undefined ? name : "";
            this.employeenum = employeenum !== undefined ? employeenum : "";
            this.department = department !== undefined ? department : "";
            this.checkin = checkin !== undefined ? checkin : "";
            this.checkout = checkout !== undefined ? checkout : "";
            this.attendrule = attendrule !== undefined ? attendrule : "";
            this.attendresult = attendresult !== undefined ? attendresult : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.date);
            __os.writeString(this.name);
            __os.writeString(this.employeenum);
            __os.writeString(this.department);
            __os.writeString(this.checkin);
            __os.writeString(this.checkout);
            __os.writeString(this.attendrule);
            __os.writeInt(this.attendresult);
        },
        function(__is)
        {
            this.date = __is.readString();
            this.name = __is.readString();
            this.employeenum = __is.readString();
            this.department = __is.readString();
            this.checkin = __is.readString();
            this.checkout = __is.readString();
            this.attendrule = __is.readString();
            this.attendresult = __is.readInt();
        },
        11, 
        false);
    Slice.defineSequence(WebAPI, "AAQListHelper", "WebAPI.AAQRslt", false);

    /**
     * @brief  签到查询的返回。
     **/
    WebAPI.AAST = Slice.defineStruct(
        function(code, AttendCounter, pageNum, pageSize, totalCount, aaqlist)
        {
            this.code = code !== undefined ? code : 0;
            this.AttendCounter = AttendCounter !== undefined ? AttendCounter : 0;
            this.pageNum = pageNum !== undefined ? pageNum : 0;
            this.pageSize = pageSize !== undefined ? pageSize : 0;
            this.totalCount = totalCount !== undefined ? totalCount : 0;
            this.aaqlist = aaqlist !== undefined ? aaqlist : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            __os.writeInt(this.AttendCounter);
            __os.writeInt(this.pageNum);
            __os.writeInt(this.pageSize);
            __os.writeInt(this.totalCount);
            WebAPI.AAQListHelper.write(__os, this.aaqlist);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.AttendCounter = __is.readInt();
            this.pageNum = __is.readInt();
            this.pageSize = __is.readInt();
            this.totalCount = __is.readInt();
            this.aaqlist = WebAPI.AAQListHelper.read(__is);
        },
        21, 
        false);

    /**
     * @brief  迎宾语。
     **/
    WebAPI.WWInfo = Slice.defineStruct(
        function(type, welcword, weleordid)
        {
            this.type = type !== undefined ? type : 0;
            this.welcword = welcword !== undefined ? welcword : "";
            this.weleordid = weleordid !== undefined ? weleordid : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.type);
            __os.writeString(this.welcword);
            __os.writeInt(this.weleordid);
        },
        function(__is)
        {
            this.type = __is.readInt();
            this.welcword = __is.readString();
            this.weleordid = __is.readInt();
        },
        9, 
        false);
    Slice.defineSequence(WebAPI, "WWlistHelper", "WebAPI.WWInfo", false);

    /**
     * @brief  迎宾语结构。
     **/
    WebAPI.WWST = Slice.defineStruct(
        function(code, welcowords)
        {
            this.code = code !== undefined ? code : 0;
            this.welcowords = welcowords !== undefined ? welcowords : null;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.code);
            WebAPI.WWlistHelper.write(__os, this.welcowords);
        },
        function(__is)
        {
            this.code = __is.readInt();
            this.welcowords = WebAPI.WWlistHelper.read(__is);
        },
        5, 
        false);

    /**
     * @brief  会议参会人员。
     **/
    WebAPI.ConferenceAttendee = Slice.defineStruct(
        function(name, photo)
        {
            this.name = name !== undefined ? name : "";
            this.photo = photo !== undefined ? photo : null;
        },
        true,
        function(__os)
        {
            __os.writeString(this.name);
            WebAPI.FileUploadHelper.write(__os, this.photo);
        },
        function(__is)
        {
            this.name = __is.readString();
            this.photo = WebAPI.FileUploadHelper.read(__is);
        },
        2, 
        false);
    Slice.defineSequence(WebAPI, "SeqConfAttendeeHelper", "WebAPI.ConferenceAttendee", false);

    WebAPI.FaceShow = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::WebAPI::FaceShow"
        ],
        -1, undefined, undefined, false);

    WebAPI.FaceShowPrx = Slice.defineProxy(Ice.ObjectPrx, WebAPI.FaceShow.ice_staticId, undefined);

    Slice.defineOperations(WebAPI.FaceShow, WebAPI.FaceShowPrx,
    {
        "AccountCheck": [, , , , , , [[WebAPI.Account]], [[WebAPI.AcntRslt]], , , ],
        "AccountAdd": [, , , , , , [[WebAPI.Account]], [[WebAPI.AcntRslt]], , , ],
        "AccountDelete": [, , , , , , [[WebAPI.Account]], [[WebAPI.AcntRslt]], , , ],
        "AccountModefy": [, , , , , , [[WebAPI.Account]], [[WebAPI.AcntRslt]], , , ],
        "AccountQuery": [, , , , , , , [[WebAPI.AcntListRlt]], , , ],
        "CamAdd": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamsListRlt]], , , ],
        "CamDelete": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamsListRlt]], , , ],
        "CamModefy": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamsListRlt]], , , ],
        "CamQuery": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamsListRlt]], , , ],
        "SigCamQuery": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamsListRlt]], , , ],
        "ChkCamStart": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamST]], , , ],
        "ChkRsltQuery": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamST]], , , ],
        "ChkCamStop": [, , , , , , [[WebAPI.CamInfo]], [[WebAPI.CamST]], , , ],
        "PicUpload": [, , , , , , [[WebAPI.FileInfo]], [[WebAPI.PeoST]], , , ],
        "PicQuery": [, , , , , , [[WebAPI.FileInfo]], [[WebAPI.PeoST]], , , ],
        "PicDelete": [, , , , , , [[WebAPI.PersonIdType]], [[WebAPI.PeoST]], , , ],
        "PicModefy": [, , , , , , [[WebAPI.PersonInfo]], [[WebAPI.PeoST]], , , ],
        "PicUpdate": [, , , , , , [[WebAPI.Mpic]], [[WebAPI.PeoST]], , , ],
        "HistoryQuery": [, , , , , , [[WebAPI.HisInfo]], [[WebAPI.AcrdQueryRslt]], , , ],
        "HistoryDelete": [, , , , , , [[3]], [[WebAPI.AcrdQueryRslt]], , , ],
        "HistoryGroup": [, , , , , , [[WebAPI.GroupModefy]], [[WebAPI.AcrdQueryRslt]], , , ],
        "CompanyAdd": [, , , , , , [[7]], [[WebAPI.OperST]], , , ],
        "CompanyDelete": [, , , , , , [[3]], [[WebAPI.OperST]], , , ],
        "CompanyQuery": [, , , , , , , [[WebAPI.OperST]], , , ],
        "DeptAdd": [, , , , , , [[7]], [[WebAPI.DeptST]], , , ],
        "DeptDelete": [, , , , , , [[3]], [[WebAPI.DeptST]], , , ],
        "DeptQuery": [, , , , , , , [[WebAPI.DeptST]], , , ],
        "PositAdd": [, , , , , , [[7]], [[WebAPI.PositST]], , , ],
        "PositDelete": [, , , , , , [[3]], [[WebAPI.PositST]], , , ],
        "PositQuery": [, , , , , , , [[WebAPI.PositST]], , , ],
        "AttendRuleAdd": [, , , , , , [[WebAPI.AttendRuleInfo]], [[WebAPI.AttRuleSt]], , , ],
        "AttnedRuleDelete": [, , , , , , [[WebAPI.AttendRuleInfo]], [[WebAPI.AttRuleSt]], , , ],
        "AttnedRuleModefy": [, , , , , , [[WebAPI.AttendRuleInfo]], [[WebAPI.AttRuleSt]], , , ],
        "AttnedRuleQuery": [, , , , , , [[WebAPI.AttendRuleInfo]], [[WebAPI.AttRuleSt]], , , ],
        "AttenAccordQuery": [, , , , , , [[WebAPI.AAQueryInfo]], [[WebAPI.AAST]], , , ],
        "AbAttenAccordQuery": [, , , , , , [[WebAPI.AAQueryInfo]], [[WebAPI.AAST]], , , ],
        "WelWordAdd": [, , , , , , [[WebAPI.WWInfo]], [[WebAPI.WWST]], , , ],
        "WelWordQuery": [, , , , , , , [[WebAPI.WWST]], , , ],
        "WelWordDelete": [, , , , , , [[WebAPI.WWInfo]], [[WebAPI.WWST]], , , ],
        "AddConference": [, , , , , , [[7]], [[7]], , , ],
        "DelConference": [, , , , , , [[3]], [[7]], , , ],
        "ModConference": [, , , , , , [[3], [7]], [[7]], , , ],
        "QueryAllConfInfo": [, , , , , , , [[7]], , , ],
        "AddConfAttendees": [, , , , , , [[3], ["WebAPI.SeqConfAttendeeHelper"]], [[7]], , , ],
        "DelConfAttendees": [, , , , , , [[3], [3]], [[7]], , , ],
        "ModConfAttendees": [, , , , , , [[3], [3], [WebAPI.ConferenceAttendee]], [[7]], , , ],
        "QueryConfInfo": [, , , , , , [[3]], [[7]], , , ],
        "QueryConfAttendingStatus": [, , , , , , [[3], [3], [3]], [[7]], , , ],
        "QueryConfAttendeeStatus": [, , , , , , [[3], [3]], [[7]], , , ],
        "shutdown": [, , , , , , , , , , ]
    });
    exports.WebAPI = WebAPI;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
